### ISSUE TITLE
"event movie night from 14 december 9pm to 10pm" doesn't respond

### ISSUE THREAD

**Issue by wonew** [cs2103aug2015-f10-4j/main#114]
same for "event korea trip from 16 december 4pm to 10 january 3pm"
same for "event korea trip from 16/12 4pm to 10/1 3pm"

**Comment by jtwjing** [comment]
First 2 is resolved.
3rd bug is because year is not specified and so default year is this year. I will try and fix it.

**Comment by jtwjing** [comment]
Fixed
