### ISSUE TITLE
Format to add dates far from now

### ISSUE THREAD

**Issue by wonew** [cs2103aug2015-f10-4j/main#133]

**Comment by jtwjing** [comment]
I dont understand this bug

**Comment by varunpatro** [comment]
@jtwjing try experimenting with dates like 12 january, 29 feburary.

We want to test whether jchronic captures dates far into the future. We also want to test whether it captures years properly.

**Comment by jtwjing** [comment]
Like when you type 01/01 and date is passed it gives 01/01/2016 instead of 01/01/2015? 

I did this yesterday for your korea trip bug already
