### ISSUE TITLE
Each member to do product review on existing tasking products

### ISSUE THREAD

**Issue by wonew** [cs2103aug2015-f10-4j/main#21]
Joey - todo.txt
James - Google Calendar
Varun - Fantastical
June - Wunderlist

**Comment by varunpatro** [comment]
**Product:** Fantastical 
**Documented by:** Varun Kumar Patro

## **Strengths:**
1. Natural Language Processing
2. Full time zone support
3. Set time and geofence alerts
4. Integration with iOS and Mac
5. Multi-lingual
6. Well designed UI and UX

## **Weaknesses:**
1. Expensive
2. Persistent process (always on)
3. Task/Reminders don't have a deadline option
4. Not allowed to create collaborative lists (single user).

**Comment by yeojoey** [comment]
**Product:** Todo.txt
**Documented by:** Yeo Joey

## **Strengths:**
1. Stores your todo list in a .txt file that can be opened, edited and viewed on any system.
2. Readable text-only interface for those who like a simple UI
3. Done tasks are saved in a separate done.txt for easy referencing
4. It's both a program and a notation system for todo lists

## **Weaknesses**
1. Difficult to launch on Windows for a new user, as it involves downloading a Unix shell
2. The command line interface may not be intuitive for new users
3. If there are many items on the list, it quickly becomes unreadable
4. No specific field for task deadlines, so no alerts

**Comment by wonew** [comment]
**Product:** Wunderlist
**Documented by:**  June Lim

## **Strengths:**
1. Able to share lists with other people
2. Able to toggle between week view, day view, individual list view
3. Keyboard shortcuts for creating new lists / creating new task / mark a task as done
4. Smart enough to recognise keywords like the days of the week / dates to auto set your deadline
5. Ability to set reminders, due dates, notes, subtasks all on 1 screen
6. Completed items are automatically hidden and only shown when requested (reduces screen clutter)
7. Ability to make tasks recur if it happens every week/month/year/custom
8. Ability to publish a list to the cloud so that anyone with the URL can access the list
9. Ability to create separate lists for separate aspects of life (e.g. work, private, school)
10. Syncs automatically to the cloud, also has manual syncing
11. Cross-platform support: Windows, OS X, web, Android, iOS
12. Easy task management including due dates, reminders, star, and list groups (contexts)
13. Email, print, and “cloud sharing” options for tasks lists
14. can use hashtags to link items that are related to items in other lists

## **Weaknesses:**
1. No location field for tasks with location
2. No start date for tasks
3. Unable to colour-code tasks/list for easy differentiation
4. Not able to set different priority for tasks

**Comment by jtwjing** [comment]
**Product:** Google Calendar
**Documented by:**  James Tan

## **Strengths:**
1.  User Interface Customization
   1. Daily, Monthly, Weekly calendar view
   2. Agenda view
2.  Can be synced with multiple platforms like PC and smartphone etc. 
3.  Can create calendar items according to category and choose to display them or not on the calendar
4.  Can be import other’s calendars i.e. Public Holidays in Singapore, friend’s calendars
5.  Notifications by email or pop-up
6.  Calendar event
   1.    Video call option
   2.    Location
   3.    Description
   4.    Attachments
   5.    Repeat (Daily, Weekly, Monthly etc.)
      f.  Guests
7.  Today icon to return to current day
8.  Option to undo added/removed events
9.  Print option
10. Search option

## **Weaknesses:**
1.  Unable to change font/view of calendar events on calendar
2.  Display Density function unnecessary
3.  Cannot see description/attachments etc. from normal calendar view; must enter edit mode
4.  Not coloured coded on the sidebar calendar; only coloured on main-view calendar  No way to differentiate from overview

**Comment by wonew** [comment]
Done.
