### ISSUE TITLE
Do Project Manual V0.0

### ISSUE THREAD

**Issue by jtwjing** [cs2103aug2015-f10-4j/main#26]

**Comment by wonew** [comment]
Hey people! Do go to this link http://www.comp.nus.edu.sg/~cs2103/AY1516S1/ (Ctrl + F: V0.0 of the Project Manual) to read the requirements of v0.0 

and

http://www.comp.nus.edu.sg/~cs2103/AY1516S1/ (Ctrl + F: common issues) for common issues in v0.0 to avoid losing marks unnecesarily

and

There's a downloadable word document from the CS2103 website http://www.comp.nus.edu.sg/~cs2103/AY1516S1/ (Sidebar > click on Project > Ctrl + F: this file) that is a template of what the manual should look like
