### ISSUE TITLE
change add command to include new floating task specs

### ISSUE THREAD

**Issue by wonew** [cs2103aug2015-f10-4j/main#57]
floating tasks now have 'due_date', 'time', 'recurrence' field as 'null'.

floating tasks will appear together with normal tasks when searched

**Comment by jtwjing** [comment]
FOR FLOATING
- dueDate, startTime and endTime set to "" during initializing
- checks for "" (empty string)

FOR RECURRENCE
- checks via number of arguments
- recurrence set as null if left blank
