### ISSUE TITLE
TA: Is it necessary to add the "type" all the time? Can the default behaviour be more simple?

### ISSUE THREAD

**Issue by wonew** [cs2103aug2015-f10-4j/main#61]
Varun: Agreed. We'll optimize this in the future. Keep in mind.

**Comment by wonew** [comment]
This is with regards to TA's comment in the project manual about creating tasks/events. He's suggesting that maybe users don't have to explicitly type whether they want to add a task or event.

**Comment by jtwjing** [comment]
can set default as task if you want

**Comment by jtwjing** [comment]
Removed type from add, add is default for task.
Created new command EventCommand for events
